export const Types = {
 "CREATE_POST": "CREATE_POST",
 "CREATE_COMMENT": "CREATE_COMMENT",
 "GET_POST": "GET_POST",
 "GET_POST_SUCCESS": "GET_POST_SUCCESS",
 "GET_COMMENT": "GET_COMMENT",
 "GET_COMMENT_SUCCESS": "GET_COMMENT_SUCCESS",
}